"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import os
APP = ['mikobots_studio/src/main.py']

DATA_FILES = []
assets_folder = '/Users/markkleinjan/Library/CloudStorage/OneDrive-MiKoBots/Documenten - MiKoBots/General/Besturing/software/Mikobots studio/MiKoBots_Studio/assets/images'  # Update this path

for root, dirs, files in os.walk(assets_folder):
    for file in files:
        # Create the destination path for the bundled app
        relative_path = os.path.relpath(root, assets_folder)  # Get the relative path
        destination = os.path.join('assets/images', relative_path)  # Specify the destination inside the app
        DATA_FILES.append((destination, [os.path.join(root, file)]))

assets_folder = '/Users/markkleinjan/Library/CloudStorage/OneDrive-MiKoBots/Documenten - MiKoBots/General/Besturing/software/Mikobots studio/MiKoBots_Studio/assets/MiKoBots_data'
for root, dirs, files in os.walk(assets_folder):
    for file in files:
        # Create the destination path for the bundled app
        relative_path = os.path.relpath(root, assets_folder)  # Get the relative path
        destination = os.path.join('assets/MiKoBots_data', relative_path)  # Specify the destination inside the app
        DATA_FILES.append((destination, [os.path.join(root, file)]))


OPTIONS = {
    'argv_emulation': False,
    'iconfile': '/Users/markkleinjan/Library/CloudStorage/OneDrive-MiKoBots/Documenten - MiKoBots/General/Besturing/software/Mikobots studio/MiKoBots_Studio/assets/images/logo 2.icns',
}

setup(
    name='MiKoBots Studio',  # Set your app's name here
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
